services:
    kaemo_import_command:
      class: KaemoTestBundle\Command\ImportMoviesCommand
      arguments: ['@doctrine', %xml_path%, '@logger']
      tags:
          - { name: console.command }

    kaemo_create_movie_command:
      class: KaemoTestBundle\Command\CreateMovieCommand
      arguments: ['@doctrine', '@logger']
      tags:
          - { name: console.command }